import { NavigationItem, WorkbenchTool, SelectedProject, FloppyProject, NoteArticle } from './types';

export const NAVIGATION_ITEMS: NavigationItem[] = [
  { label: '/INDEX', href: '#top' },
  { label: '/PROFILE', href: '#profile' },
  { label: '/WORKS', href: '#works' },
  { label: '/NOTES', href: '#notes' },
  { label: '/CONTACT', href: '#contact' },
];

export const WORKBENCH_TOOLS: WorkbenchTool[] = [
  { index: '01', name: 'ChatGPT × Codex' },
  { index: '02', name: 'Claude Code' },
  { index: '03', name: 'Grok Build' },
  { index: '04', name: 'MiMo Code' },
  { index: '05', name: 'OpenCode' },
  { index: '06', name: 'Antigravity' },
  { index: '07', name: 'TRAE' },
  { index: '08', name: 'WorkBuddy' },
  { index: '09', name: 'OpenClaw' },
  { index: '10', name: 'Hermes Agent' },
  { index: '11', name: 'Self-hosted Agents' },
];

export const SELECTED_PROJECTS: SelectedProject[] = [
  {
    id: 'milestone',
    number: '01',
    name: 'Milestone OS',
    label: 'PRODUCTIVITY SYSTEM',
    description: '面向个人知识、任务与长期记录的 Web-first 工作系统。',
    image: '/works/milestone.jpg',
    status: 'OPEN',
    tags: 'System design · Knowledge ops · AI workflow',
    url: 'https://milestone.jintao.co.uk/',
  },
  {
    id: 'reader',
    number: '02',
    name: '朝夕读报 · Reader',
    label: 'DAILY READER',
    description: '聚合 AI 与自定义主题的每日剪报阅读器，兼顾热度与个人筛选。',
    image: '/works/reader.jpg',
    status: 'OPEN',
    tags: 'Information architecture · Daily curated feeds',
    url: 'https://reader.jintao.co.uk/',
  },
  {
    id: 'prompt-notebook',
    number: '03',
    name: 'Prompt Notebook',
    label: 'VISUAL PROMPTS',
    description: '自托管的视觉 Prompt 笔记本，支持加密保存 AI 与图床设置。',
    image: '/works/prompt.jpg',
    status: 'OPEN',
    tags: 'Frontend craft · AI imaging · Workflow',
    url: 'https://prompt.jintao.co.uk/',
  },
  {
    id: 'aihub',
    number: '04',
    name: 'ACKS Image Web',
    label: 'AI PRODUCT',
    description: '面向真实使用场景的 AI 生图体验工具，也是 ACKS AI 实践的一部分。',
    image: '/works/aihub.jpg',
    status: 'PRIVATE',
    tags: 'AI integration · Product delivery · Operations',
    url: 'https://aihub.jintao.co.uk/',
  },
  {
    id: 'gallery',
    number: '05',
    name: 'Personal Gallery',
    label: 'VISUAL ARCHIVE',
    description: '独立维护的个人视觉档案，把照片与生活片段留在自己的空间里。',
    image: '/works/gallery.jpg',
    status: 'OPEN',
    tags: 'Visual system · Self-hosting · Curation',
    url: 'https://gallery.jintao.co.uk/',
  },
  {
    id: 'note-os',
    number: '06',
    name: 'Note OS',
    label: 'Note OS',
    description: '个人OS，集成日记，笔记，任务管理和AI Agent',
    image: '/uploads/projects/907f27b26657c9534071e4fa65c5eb1e8eb6d86b533d4f0b687a610b8f90ce46.png',
    status: 'OPEN',
    tags: 'Product · Design · Engineering',
    url: 'https://note.jintao.co.uk/',
  },
  {
    id: 'acks-watermarker',
    number: '07',
    name: 'ACKS Watermarker',
    label: 'IMAGE TOOL',
    description: '浏览器端图片水印工作室，支持图文水印、拖拽编辑、批量处理、本地修复与隐私友好导出。',
    image: '/works/acks-watermarker.png',
    status: 'OPEN',
    tags: 'Canvas · Local-first · Batch export',
    url: 'https://jintao.co.uk/watermark',
  },
];

export const FLOPPY_PROJECTS: FloppyProject[] = [
  {
    id: 'acks-watermarker-repo',
    name: 'ACKS-Watermarker',
    summary: '浏览器端图片水印工作室，支持图文水印、拖拽编辑、批处理、本地修复、抠图与隐私友好导出。',
    repositoryUrl: 'https://github.com/shynloc/ACKS-Watermarker',
    stack: 'HTML5 · JavaScript · Canvas API',
    platform: 'Web Tool · Browser',
    version: 'v1.0.0',
    color: 'teal',
    visible: true,
  },
  {
    id: 'prompt-notebook-repo',
    name: 'Prompt Notebook',
    summary: '自托管的视觉 Prompt 笔记本，支持加密保存 AI 与图床设置。',
    repositoryUrl: 'https://github.com/shynloc/prompt-notebook',
    stack: 'TypeScript · React',
    platform: 'Web · Self-hosted',
    version: 'v1.0.0',
    color: 'blue',
    visible: true,
  },
  {
    id: 'r2-local-pic-manager',
    name: 'R2 Local Pic Manager',
    summary: '基于 Cloudflare R2 与 Worker 的本地图床管理器。',
    repositoryUrl: 'https://github.com/shynloc/CloudFlare-R2-LocalPicManager',
    stack: 'HTML · Cloudflare Worker',
    platform: 'Tool · Self-hosted',
    version: 'v1.0.0',
    color: 'amber',
    visible: true,
  },
  {
    id: 'hermes-office-suite',
    name: 'Hermes Office Suite',
    summary: '面向 Hermes Agent 的中文办公自动化技能套件，覆盖 Word、Excel、PDF 与 PPT。',
    repositoryUrl: 'https://github.com/shynloc/Hermes-Easy-Office-Suite',
    stack: 'Python · Automation',
    platform: 'Agent Skill',
    version: 'v1.0.0',
    color: 'plum',
    visible: true,
  },
  {
    id: 'memos-web-clipper',
    name: 'Memos Web Clipper',
    summary: '把网页正文或选中文本以 Markdown 形式保存到自部署的 Memos。',
    repositoryUrl: 'https://github.com/shynloc/memos-web-clipper',
    stack: 'JavaScript · Browser API',
    platform: 'Chrome Extension',
    version: 'MAIN',
    color: 'amber',
    visible: true,
  },
  {
    id: 'acks-memos-mcp-server',
    name: 'ACKS Memos MCP',
    summary: '把自托管 Memos 连接到主流 AI 模型与 Agent 的 MCP 服务端。',
    repositoryUrl: 'https://github.com/shynloc/acks-memos-mcp-server',
    stack: 'TypeScript · MCP',
    platform: 'Server · Docker',
    version: 'v1.0.1',
    color: 'olive',
    visible: true,
  },
  {
    id: 'hermes-agent-qq-plugin',
    name: 'Hermes Agent QQ',
    summary: '适配 Hermes Agent 的 QQ 聊天插件，让 Agent 可以通过 QQ 进行沟通。',
    repositoryUrl: 'https://github.com/shynloc/Hermes-Agent-QQ-Plugin',
    stack: 'Python · Agent Plugin',
    platform: 'Server · QQ',
    version: 'v1.2.1',
    color: 'blue',
    visible: true,
  },
  {
    id: 'telegram-voice-skill',
    name: 'Telegram Voice Skill',
    summary: '帮助 AI 助手可靠发送 Telegram 语音消息的实战技能包。',
    repositoryUrl: 'https://github.com/shynloc/telegram-voice-message-skill',
    stack: 'Shell · Telegram API',
    platform: 'Agent Skill',
    version: 'v1.0.0',
    color: 'ivory',
    visible: true,
  },
];

export const NOTE_ARTICLES: NoteArticle[] = [
  {
    id: 'note-590',
    url: 'https://jintaoblog.com/posts/590.html',
    date: '2026-08-08',
    year: '2026',
    month: '08',
    day: '08',
    category: 'NOTES',
    readTime: 31,
    title: '怎么跟 AI 说话，它才听得懂？',
    summary: '从底层机制到实战模板，一次讲透 先看两个真实的对话。 A 同学： 帮我写个竞品分析 A…',
    featured: true,
    tag: 'NOTES',
  },
  {
    id: 'note-589',
    url: 'https://jintaoblog.com/posts/589.html',
    date: '2026-08-06',
    month: '08',
    day: '06',
    category: 'NOTES',
    readTime: 5,
    title: '0基础也能用 Workbuddy 建站💡',
    summary: '想建网站，却被「服务器」「域名」「IP」「解析」这些词劝退？ 别慌。这篇文章用开公司的大白话，带你一次搞懂，顺便看看 W…',
  },
  {
    id: 'note-585',
    url: 'https://jintaoblog.com/posts/585.html',
    date: '2026-08-02',
    month: '08',
    day: '02',
    category: 'AI STUDY',
    readTime: 5,
    title: 'Vibe Coding 时代的个人软件工程：如何利用多个 AI Agent 完成项目接力开发',
    summary: '过去的软件开发，核心能力是程序员编写代码。 而进入 AI Agent 时代之后，一个新的问题正在出现： 如果代码越来越多…',
  },
  {
    id: 'note-584',
    url: 'https://jintaoblog.com/posts/584.html',
    date: '2026-07-31',
    year: '2026',
    month: '07',
    day: '31',
    category: 'NOTES',
    readTime: 32,
    title: 'Workbench Builder Skill.md — 个人工作台搭建器 v5',
    summary: '帮非技术用户从一句模糊需求搭出成熟、稳定、可迭…',
  },
  {
    id: 'note-583',
    url: 'https://jintaoblog.com/posts/583.html',
    date: '2026-07-30',
    month: '07',
    day: '30',
    category: 'NOTES',
    readTime: 7,
    title: '搭建一个 Agent 的完整知识图谱',
    summary: '一、先搞清楚 Agent 到底是什么 最简单的定义： Agent = LLM（…',
  },
  {
    id: 'note-557',
    url: 'https://jintaoblog.com/posts/557.html',
    date: '2026-07-30',
    month: '07',
    day: '30',
    category: 'AI STUDY',
    readTime: 6,
    title: 'AI生成图片版权归属完整分析：Grok、Gemini、ChatGPT三大平台对比',
    summary: 'AI 生成图片，版权到底算谁的？Grok / Gemini / ChatGPT 三大平台完整对比 最近身边越来越多人在问…',
  },
];
